FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

ENV DOCKER=TRUE

RUN pip install -r requirements.txt

RUN apt update && apt install -y vim

COPY . .

CMD [ "./scripts/start_celery.sh" ]