FROM node:20 AS frontend-builder

WORKDIR /client

COPY ./client . 
RUN npm install
RUN npm run build

FROM python:3.12

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
ENV DOCKER=TRUE

COPY . /app

COPY --from=frontend-builder /client /app/client

CMD [ "./scripts/start_gunicorn.sh" ]