services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    volumes:
      - ./client:/app/client
    environment:
      - DOCKER=TRUE
    ports:
      - 8000:8000
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - DOCKER=TRUE
      - OPENLIBRARY_SESSION_COOKIE=${OPENLIBRARY_SESSION_COOKIE}
    env_file:
      - .env
  redis:
    image: "redis:alpine"