FROM node:20 AS frontend-builder

WORKDIR /app

COPY . .
RUN npm install
RUN npm run build

FROM python:3.12

WORKDIR /app

COPY --from=frontend-builder /app /app

RUN pip install -r requirements.txt
ENV DOCKER=TRUE
CMD [ "./scripts/start_gunicorn.sh" ]